# Generated by Django 5.2.12 on 2026-03-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer_seconds', models.PositiveIntegerField(default=15, help_text='Seconds allowed per question (e.g. 10, 15, 20).')),
                ('points_per_question', models.PositiveIntegerField(default=10, help_text='Points awarded for each correct answer.')),
            ],
            options={
                'verbose_name': 'Game Settings',
                'verbose_name_plural': 'Game Settings',
            },
        ),
    ]
